fix CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,4 +55,4 @@ jobs:
             ./build.sh
             version=$(cat version.txt)
             if [ ! -f "dist/torqify_tf_backend.$version.sh" ]; then echo "Error: torqify_tf_backend bash script wasn't reated" && exit 1; fi
-            if [ ! -f "torqify_tf_backend.$version.tar.gz" ]; then echo "Error: torqify_tf_backend python tar.gz wasn't created" && exit 1; fi
+            if [ ! -f "dist/torqify_tf_backend.$version.tar.gz" ]; then echo "Error: torqify_tf_backend python tar.gz wasn't created" && exit 1; fi
